#ifndef ABSTRACTCONINTERFACE_GLOBAL_H
#define ABSTRACTCONINTERFACE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ABSTRACTCONINTERFACE_LIBRARY)
#  define ABSTRACTCONINTERFACE_EXPORT Q_DECL_EXPORT
#else
#  define ABSTRACTCONINTERFACE_EXPORT Q_DECL_IMPORT
#endif

#endif // ABSTRACTCONINTERFACE_GLOBAL_H
